# Generated by Django 2.0 on 2018-03-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.SlugField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=500)),
            ],
        ),
    ]
