# Generated by Django 2.0 on 2018-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=500, verbose_name='Country'),
        ),
    ]
