# Generated by Django 2.0 on 2018-03-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0002_auto_20180314_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, verbose_name='Book title')),
                ('publication_date', models.DateField(blank=True)),
                ('authors', models.ManyToManyField(to='opp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(default='0')),
                ('chapter_name', models.CharField(max_length=100, verbose_name='Chapter name')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('website', models.URLField(blank=True)),
                ('country', models.ManyToManyField(to='opp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.SlugField(primary_key=True, serialize=False, verbose_name='Subject code')),
                ('subject_name', models.CharField(max_length=500, verbose_name='Subject')),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('Primary', 'Primary school'), ('Secondary', 'Secondary school'), ('SH', 'High school'), ('UG', 'Undergrad'), ('Grad', 'Graduate')], max_length=1)),
                ('book', models.ManyToManyField(to='opp.Book')),
                ('country', models.ManyToManyField(to='opp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.SlugField(primary_key=True, serialize=False, verbose_name='Topic ID')),
                ('topic_name', models.CharField(max_length=500, verbose_name='Topic name')),
                ('description', models.TextField(blank=True)),
                ('chapter', models.ManyToManyField(to='opp.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='topic',
            field=models.ManyToManyField(to='opp.Topic'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Publisher'),
        ),
    ]
