# Generated by Django 2.0 on 2018-03-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0003_auto_20180314_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary-school'), ('Secondary', 'Secondary-school'), ('SH', 'High-school'), ('UG', 'Undergrad'), ('Grad', 'Graduate')], max_length=1),
        ),
    ]
