# Generated by Django 2.0 on 2018-03-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0005_auto_20180315_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=500, verbose_name='Problem name')),
                ('text', models.TextField()),
                ('template', models.CharField(max_length=500, verbose_name='Problem Template')),
                ('number_of_steps', models.PositiveIntegerField(default=0)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Topic', verbose_name='Topic ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('topic_id', 'problem_name')},
        ),
    ]
