# Generated by Django 2.0 on 2018-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0009_auto_20180315_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('solucion', models.CharField(max_length=100)),
            ],
        ),
    ]
