# Generated by Django 2.0 on 2018-03-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0010_student_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.SlugField(primary_key=True, serialize=False, verbose_name='School code')),
                ('school_name', models.CharField(max_length=500, verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=100)),
                ('number_solved_problems', models.IntegerField(default='0')),
                ('country', models.ManyToManyField(to='opp.Country')),
                ('school', models.ManyToManyField(to='opp.School')),
            ],
        ),
    ]
