# Generated by Django 2.0 on 2018-03-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0011_school_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_ID',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opp.Country', verbose_name='Country name'),
            preserve_default=False,
        ),
    ]
