# Generated by Django 2.0 on 2018-03-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0014_auto_20180320_0246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('group', 'person')},
        ),
    ]
