# Generated by Django 2.0 on 2018-03-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0015_auto_20180320_0252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
    ]
