# Generated by Django 2.0 on 2018-03-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0018_auto_20180320_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
