# Generated by Django 2.0 on 2018-03-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0022_auto_20180320_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opp.Group'),
            preserve_default=False,
        ),
    ]
