# Generated by Django 2.0 on 2018-03-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0025_auto_20180320_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opp.Group'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ManyToManyField(to='opp.Person'),
        ),
    ]
