# Generated by Django 2.0 on 2018-03-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0026_auto_20180321_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'test')},
        ),
    ]
