# Generated by Django 2.0 on 2018-03-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0028_auto_20180322_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_members', through='opp.Membership', to='opp.Person'),
        ),
    ]
