# Generated by Django 2.0 on 2018-03-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0030_auto_20180322_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='opp.Person'),
            preserve_default=False,
        ),
    ]
