# Generated by Django 2.0 on 2018-03-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0032_auto_20180323_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='person',
            name='test',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
