# Generated by Django 2.0 on 2018-03-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0033_auto_20180323_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='chapter',
            field=models.ManyToManyField(to='opp.Chapter'),
        ),
    ]
