# Generated by Django 2.0 on 2018-03-23 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0034_subject_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='associated_steps',
        ),
        migrations.AddField(
            model_name='step',
            name='problem_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opp.Problem', verbose_name='Problem ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('problem_name', 'step_name')},
        ),
    ]
