# Generated by Django 2.0 on 2018-03-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0035_auto_20180323_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='topic_id',
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='step',
            name='problem_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='substep',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='substep',
            name='step_name',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Substep',
        ),
    ]
