# Generated by Django 2.0 on 2018-03-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0037_auto_20180323_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=500, verbose_name='Step name')),
                ('explanation', models.TextField()),
                ('video', models.CharField(max_length=500)),
                ('instruction', models.TextField()),
                ('number_of_substeps', models.PositiveIntegerField(default=0)),
                ('problem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Problem', verbose_name='Problem ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('problem_name', 'step_name')},
        ),
    ]
