# Generated by Django 2.0 on 2018-03-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0038_auto_20180323_1335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
    ]
