# Generated by Django 2.0 on 2018-03-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0042_remove_step_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='problem_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opp.Problem', verbose_name='Problem ID'),
            preserve_default=False,
        ),
    ]
