# Generated by Django 2.0 on 2018-03-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0043_step_problem_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('problem_name', 'step_name')},
        ),
    ]
