# Generated by Django 2.0 on 2018-03-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0044_auto_20180323_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.SlugField(primary_key=True, serialize=False, verbose_name='School code')),
                ('school_name', models.CharField(max_length=500, verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('number_solved_problems', models.IntegerField(default='0')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Country', verbose_name='Country name')),
                ('school', models.ManyToManyField(to='opp.School')),
            ],
        ),
        migrations.CreateModel(
            name='Substep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substep_name', models.CharField(max_length=500, verbose_name='Substep name')),
                ('answer', models.TextField()),
                ('hint', models.TextField()),
                ('step_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Step', verbose_name='Step ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='substep',
            unique_together={('step_name', 'substep_name')},
        ),
    ]
