# Generated by Django 2.0 on 2018-03-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0046_auto_20180323_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tries', models.IntegerField(default='0')),
                ('problem_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.StudentProblem')),
                ('step_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Step')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stepstudent',
            unique_together={('problem_student_id', 'step_student_id')},
        ),
    ]
