# Generated by Django 2.0 on 2018-03-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0047_auto_20180323_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstepStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substep_name', models.CharField(default='0', max_length=100)),
                ('answer', models.CharField(default='0', max_length=500)),
                ('number_of_tries', models.IntegerField(default='0')),
                ('step_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.StepStudent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='substepstudent',
            unique_together={('step_student_id', 'substep_name')},
        ),
    ]
