# Generated by Django 2.0 on 2018-03-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0048_auto_20180323_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentproblem',
            old_name='number_of_tries',
            new_name='fail_attemps',
        ),
        migrations.AddField(
            model_name='studentproblem',
            name='succesful_attemps',
            field=models.IntegerField(default='0'),
        ),
    ]
