# Generated by Django 2.0 on 2018-03-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0049_auto_20180326_0141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substepstudent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='substepstudent',
            name='step_student_id',
        ),
        migrations.RenameField(
            model_name='stepstudent',
            old_name='number_of_tries',
            new_name='fail_attemps',
        ),
        migrations.AddField(
            model_name='stepstudent',
            name='number_of_substeps',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='stepstudent',
            name='succesful_attemps',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='SubstepStudent',
        ),
    ]
