# Generated by Django 2.0 on 2018-03-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0050_auto_20180326_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepStudent',
            new_name='StudentStep',
        ),
    ]
