# Generated by Django 2.0 on 2018-03-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0052_studentproblem_answer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='problem_name',
            new_name='problem_id',
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('problem_id', 'step_name')},
        ),
    ]
