# Generated by Django 2.0 on 2018-03-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0053_auto_20180326_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substep',
            old_name='step_name',
            new_name='step_id',
        ),
        migrations.AlterUniqueTogether(
            name='substep',
            unique_together={('step_id', 'substep_name')},
        ),
    ]
