# Generated by Django 2.0 on 2018-03-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0056_auto_20180327_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.SlugField(primary_key=True, serialize=False, verbose_name='School code')),
                ('school_name', models.CharField(max_length=500, verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('number_solved_problems', models.IntegerField(default='0')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Country', verbose_name='Country name')),
                ('school', models.ManyToManyField(to='opp.School')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succesful_attemps', models.IntegerField(default='0')),
                ('fail_attemps', models.IntegerField(default='0')),
                ('answer_file', models.CharField(max_length=100, verbose_name='answer_file')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Problem', verbose_name='Problem ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Student', verbose_name='Topic ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succesful_attemps', models.IntegerField(default='0')),
                ('fail_attemps', models.IntegerField(default='0')),
                ('number_of_substeps', models.IntegerField(default='0')),
                ('problem_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.StudentProblem')),
                ('step_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Step')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentstep',
            unique_together={('problem_student_id', 'step_student_id')},
        ),
        migrations.AlterUniqueTogether(
            name='studentproblem',
            unique_together={('student_id', 'problem_id')},
        ),
    ]
