# Generated by Django 2.0 on 2018-03-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0057_auto_20180327_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproblem',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Student', verbose_name='Student ID'),
        ),
    ]
