# Generated by Django 2.0 on 2018-03-27 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0060_auto_20180327_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succesful_attemps', models.IntegerField(default='0')),
                ('fail_attemps', models.IntegerField(default='0')),
                ('number_of_substeps', models.IntegerField(default='0')),
                ('problem_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.StudentProblem')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opp.Step')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentstep',
            unique_together={('problem_student_id', 'step_id')},
        ),
    ]
